### ISSUE TITLE
Xiaomi Wireless Switch

### ISSUE THREAD

**Issue by davidkristof** [PatchworkBoy/homebridge-edomoticz#144]
Hey there, i'm a newbie at almost everything related to home automation :P I managed with domoticz and homebridge-edomoticz to see the xiaomi wireless switch in home app, but after setting what happens with 1 click, 2 click, long press in home app, nothing happens. I tried to figure out how to just set events and things in domoticz, but its way too complicated for me right now and adding sonoff tasmota to domoticz also a bit complicated for me. 
Anyone knows how to fix it, so i can just set actions for the switch clicks in the apple home app and i dont have to worry about domoticz?
A million thanks in advance

**Comment by xTheRamon** [comment]
I think adding events in Domoticz is the way to go, since it'll work even when you're switching from the website.
I'm not sure how you would be able to configure such functionality in the homebridge app itself without messing up Domoticz's device states. (e.g. whenever I switch my living room light, turn on my TV, and Domoticz knowing about this change)

Other than that, you'll probably need an Apple TV or iPad for this automation functionality, right?

**Comment by davidkristof** [comment]
Hey Ramon
Hi j the meantime I found a solution somewhere online. I had to add my other tasmota switches, adding Mqtt devices and creat virtual switch. That made the Xiaomi switch work through home app as I wanted to. Domoticz seems pretty awesome

**Comment by xTheRamon** [comment]
Great work! Good to hear. Closing this issue for now. :)
