### ISSUE TITLE
[Feature] Add history for Eve app

### ISSUE THREAD

**Issue by ooii** [PatchworkBoy/homebridge-edomoticz#158]
Is it possible to add history to devices reporting temperature and power consumption in order to use them with Eve?

**Comment by PatchworkBoy** [comment]
Nope. 

    On Thursday, 3 May 2018, 10:13, Farid <notifications@github.com> wrote:
 

 Is it possible to add history to devices reporting temperature and power consumption in order to use them with Eve?—

**Comment by ooii** [comment]
Any explanation why? 
It is technically undoable with this plug-in? If it is lack of time, can I try and if I succeed send a pull request?

**Comment by PatchworkBoy** [comment]
Feel free - I spent 6 months trying and got nowhere. Only proof of concept I’m aware of is here: https://gist.github.com/simont77/919399dda338e37213b1ca231082c219

That was for the original generation Eve Power accessories. The protocol has changed since then as far as I’m aware and is undocumented - Eve won’t release it as it’s closed-source and proprietary to their hardware.

**Comment by ooii** [comment]
In this case, I don't believe I can do better than you.
But I know @ebaauw has managed to have temperature history with [his Hue plugin](https://github.com/ebaauw/homebridge-hue).

**Comment by PatchworkBoy** [comment]
The matter is how to get all the history data cleanly from Domoticz' JSON API. How Hue integrates this in their own system is likely to be entirely different to how it's done in Domoticz. Generally when it comes to integrating any new features, the question is whether Domoticz exposes the required data to do what needs doing, and whether it does so in a suitable/usable format.
