### ISSUE TITLE
plugin is using the same port as config-ui

### ISSUE THREAD

**Issue by johnny-bb** [PatchworkBoy/homebridge-edomoticz#167]
Hi, i am newby  and have installed Homebridge on a raspberry pi with the plugin config-ui-x and all is working, config-ui-x uses localhost:8080 
now i am trying to install the plugin for Edomoticz but that is using the serveraddress and port wich is not working.
how can i change the the port the Edomoticz plugin is using , so that both plugins are working an reachable ?
i have tried to change the port in the config.json to 443 and set ssl:1  but that is giving me,
Error: connect ECONNREFUSED 127.0.0.1:443
who can tell me how to do this.

**Comment by PatchworkBoy** [comment]
Your problem is that Domoticz itself serves on port 8080 by default. Port 443 generally only works once you've replaced the Domoticz native cert with your own. This isn't an issue with homebridge-eDomoticz. Your SSL configuration for Domoticz itself is incorrect.

Either: tell Domoticz to serve non-SSL on a different port to config-ui-x, or vice versa, or make sure your Domoticz SSL setup is correct.
