### ISSUE TITLE
Door Lock Inverted & Garagedoor "Not Supported"

### ISSUE THREAD

**Issue by jannnfe** [PatchworkBoy/homebridge-edomoticz#171]
Hello,
"Lock Mechanisms - Domoticz SwitchTypeVal: 19" works for me but not "Lock Mechanisms (inverted) - Domoticz SwitchTypeVal: 20". The inverted version will display "Not Supported" in the Apple Home app. This is the [pull request](https://github.com/PatchworkBoy/homebridge-edomoticz/pull/146).

I also have the problem that I would like to integrate the Apple HomeKit Service Garagedoor into my HomeKit. In the [pull request](https://github.com/PatchworkBoy/homebridge-edomoticz/pull/115) it is written that the device should be called "garage" and should use the type "Door Lock". Is it possible to use the type "Lock Mechanisms (inverted) - Domoticz SwitchTypeVal: 20" and choose a other name for the Garagedoor?

Last but not least, I have another question for which I do not necessarily want to open an issue. I had already asked the question [here](https://github.com/PatchworkBoy/homebridge-edomoticz/issues/122#issuecomment-422402304), but why the status 6 (panic) is used instead of the status 2 (alarm) at the security system?

Thanks :)

**Comment by jannnfe** [comment]
Hey @PatchworkBoy 
Is there any news on the three problems? What interests me most is an answer to the last question from me in [this issue](https://github.com/PatchworkBoy/homebridge-edomoticz/issues/122), which has something to do with the alarm system.
Thanks! :)

**Comment by kazdegroot** [comment]
I had this same issue, and it seems the currently released version _does_ include the code for the inverted door, but _doesn't_ include the type id in the constants.js. This is fixed in master.

The garage door function only works for the normal door, but could probably easily be duplicated for the inverted variant. The distinction is currently made on garage being in the Domoticz name of the switch (eg 'garage door' should work also), but that would be easily adjusted when adding the inverted garage door function ;)

**Comment by jannnfe** [comment]
The creator of the plugin seems to be inactive and I do not really have the experience to take care of the problems. Do you have experience to possibly make the adjustments? :)

**Comment by PatchworkBoy** [comment]
Not inactive, just v.busy - Merged & NPMJS updated.
