### ISSUE TITLE
Configure domoticz webroot

### ISSUE THREAD

**Issue by Zenuka** [PatchworkBoy/homebridge-edomoticz#174]
I've changed the webroot for domoticz (into /domoticz) to use it behind a reverse proxy. How should I configure the plugin? Is there a way to specify the webroot? I've searched the readme's and issues but could not find anything related to this. I'm sorry if I'm missing something obvious 😊

**Comment by boscorelly** [comment]
Why do you rewrite url with your reverse proxy ?!
Simply base the redirection depending on the virtual host name...

**Comment by PatchworkBoy** [comment]
Have you tried the following in config.json...?

`"server":"user:pass@127.0.0.1/domoticz"`

**Comment by skulblaka24** [comment]
Hi there,

As there isn't any answer, I will 😉

I've tried what you suggested and it does not work... 

The reason is because when you are building your request url in the code here for example:
114         this.apiBaseURL = "http" + (this.ssl ? "s" : "") + "://" + this.server + ":" + this.port + "/json.htm?";

You add the port variable at the end. With a webroot the port should be in-between.
eg:
Current not working url: https://URL/WEBROOT:443/json.htm?
Should be: https://URL:443/WEBROOT/json.htm?

Hopes this clarify 😉

**Comment by skulblaka24** [comment]
Hi again,

I've created a pull request with the added code to handle the webroot parameter. If someone is still interested.

Have a great one !

**Comment by PatchworkBoy** [comment]
Merged in and pushed a few revisions back...
