### ISSUE TITLE
More Sensor Types?

### ISSUE THREAD

**Issue by mysteryan** [PatchworkBoy/homebridge-eDomoticz#2]
Are there any plans to implement more sensor types?  Sensors like contact, occupancy and motion sensors seems to have similar HomeKit ctypes and a wide array of domoticz virtual sensors would be supported based on this shared code...?

**Comment by PatchworkBoy** [comment]
Yup - as many types as I can work out how to support based on Domoticz's Type/SubTypes is the plan...

**Comment by PatchworkBoy** [comment]
Just thinking out loud - usefulness of kWh, general usage sensors, contact & occupancy & motion for triggers (which I assume is the ultimate requirement) isn’t immediately suited until I can make _homebridge-eDomoticz_ poll Domoticz at given intervals (2 secs being that implemented in homebridge-ZWay’s setup iirc), or I discover a way for Domoticz to notify homebridge of the event... otherwise I’m assuming the events will only be triggered when one launches or refreshes the home kit app. 

(Dunno if either Domoticz can push an event or Homebridge receive an event - will have to read up more. Only been using Domoticz/Homebridge & home automation in general for a week or so - @gizmocuz / @nfarina / @khaosT - any hints you can give here on best way to approach? Is having homebridge constantly polling a platform server frowned upon??)

**Comment by PatchworkBoy** [comment]
Ok - so the Domoticz end can push via HttpLink... so question is can Homebridge / HAP accessories be updated via http puts from the platform server, rather than gets from Homebridge?

**Comment by pepijng** [comment]
What about the MQTT option? Domoticz posts a MQTT message on every status change of any device?

**Comment by PatchworkBoy** [comment]
Same question tho - Does _Homebridge_ listen for MQTT, or HTTP puts/posts?

On the “more sensors” issue in general, I’d need the JSON output for the specific device to add support for it - see https://www.domoticz.com/wiki/Domoticz_API/JSON_URL's#Retrieve_status_of_specific_device

These should be posted as new issues per device.
