### ISSUE TITLE
API Calls to Domoticz depricated

### ISSUE THREAD

**Issue by Naqua** [PatchworkBoy/homebridge-edomoticz#265]
Hello since the last beta 15326 of domoticz the api is changed.
Domoticz produces the following in the log when edomotics plugin is started.
No problem yet but the api calls will soon be depricated and edomoticz wont work anymore.
Please refer to https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s for the correct new api calls and please change edomoticz calls accordingly thank you.

023-06-14 22:40:36.085 Status: [WebServer] Depricated RType (devices) for API request. Handled via fallback (getdevices), please use correct API Command! (127.0.0.1)
2023-06-14 22:40:36.096 Status: [WebServer] Depricated RType (devices) for API request. Handled via fallback (getdevices), please use correct API Command! (127.0.0.1)

**Comment by Git-Bruno** [comment]
I had the same problem. In fact file 'lib/domoticz.js' has been updated to use the API calls with the correct syntax but no update was offered in the Homebridge GUI , I guess because the version was unchanged. 
I fixed the problem by replacing file domoticz.js in /var/lib/homebridge/node_modules/homebridge-edomoticz  on my system by the updated one from the github repo.
Additionally I made the same change to the file index.js for the homebridge-domoticz-selector-switch  plugin (no more maintained)
Hope this helps

**Comment by Madcat-76310** [comment]
Hi, i've no domoticz.js file in /var/lib/homebridge/node_modules/homebridge-edomoticz [i've no homebridge-edomoticz directory...], how to replace this file ? Thanks

**Comment by Git-Bruno** [comment]
Hi, 
Maybe the location of the domoticz.js file shipped with the homebridge-edomoticz plugin is installation dependent.  I assume your run Linux and have the hombridge-edomoticz plugin installed.  If so, you can search for the domoticz.js file using a find command. 
Try 'find . -name domoticz.js'. This will search for the file in the current directory as well as in the subdirectories. You may first start from the /var and /opt and next from root if the file was not found.
Hope this helps.

**Comment by Madcat-76310** [comment]
I'm using a VM, my location is /domoticz/www/js, thanks for this.
I've try sudo npm update -g domoticz.js => up to date in 5s... => not solved...

**Comment by PvdGulik** [comment]
In trying to replace the domoticz.js file I also failed. And also by trying to fully deinstall and install again I have the same results. I assumed by totally deinstall and reinstall it would be solved because I install the latest version of domoticz.js. But apparently not…


Op 1 aug. 2023 om 17:19 heeft Madcat-76310 ***@***.***> het volgende geschreven:

﻿

I'm using a VM, my location is /domoticz/www/js, thanks for this.
I've try sudo npm update -g domoticz.js => up to date in 5s... => not solved...

**Comment by Git-Bruno** [comment]
@Madcat-76310
Hmm. This file is the file shipped with Domoticz.  You don't want to replace it as it is used by Domoticz itself ..this is not the file part of the homebridge-edomoticz code.
The domoticz.js file you are looking for should look like the one on this github repo in the lib directory. I installed the homebridge-edomoticz via the Homebridge Config UI X page on my systemConfig UI X and this created several directories among them the /var/lib/homebridge/node_modules/homebridge-edomoticz directory in my case. I run Mint. 
I guess the installation under a VM should produce something similar. People running Domoticz in a VM may help here.

**Comment by PatchworkBoy** [comment]
Ps:

'sudo find / -type d -name "homebridge-edomoticz"

...should tell you where all folders reside on your system called homebridge-edomoticz...

**Comment by daserra23** [comment]
I just updated for the first time in a couple of years to the latest eDomoticz but the update still causes these issues.

**Comment by GravityRZ** [comment]
i also have this problem now after updating

akamming was so nice to update his thermostat plugin to this error would not be gennerated anymore.
now it turns out that the edomoticz plugin has  the same problem

i get 13 times this error
exactly the amount of all the homebridge devices

please update the json strings send to domoticz

old code depreciated
/json.htm?type=devices&rid=IDX

new code to use
/json.htm?type=command&param=getdevices&rid=IDX

it should not be that hard to fix


2023-08-24 12:53:45.714 [WebServer] Deprecated RType (devices) for API request. Handled via fallback (getdevices), please use correct API Command! (192.168.1.50)

**Comment by DewGew** [comment]
@PatchworkBoy Npm package is not uppdated with new API

**Comment by PatchworkBoy** [comment]
It isn't that hard to fix, but I have a severely disabled child I have to care for and a dayjob, therefore, you're all just going to have to wait til I have the time available. Sorry.

    On Thursday, 24 August 2023 at 11:58:50 BST, GravityRZ ***@***.***> wrote:  
 
 


i also have this problem now after updating

akamming was so nice to update his thermostat plugin to this error would not be gennerated anymore.
now it turns out that the edomoticz plugin has the same problem

i get 13 times this error
exactly the amount of all the homebridge devices

please update the json strings send to domoticz

old code depreciated
/json.htm?type=devices&rid=IDX

new code to use
/json.htm?type=command&param=getdevices&rid=IDX

it should not be that hard to fix

2023-08-24 12:53:45.714 [WebServer] Deprecated RType (devices) for API request. Handled via fallback (getdevices), please use correct API Command! (192.168.1.50)

**Comment by GravityRZ** [comment]
take your time
family always comes first

**Comment by Naqua** [comment]
intermediate solution: (on raspberry)
Download new domoticz.js from this github
search for  the  location of edomoticz with: sudo find / -type d -name "homebridge-edomoticz"
go to lib subdirectory of edomoticz directory
stop homebridge with: sudo hb-service stop
replace domoticz.js with the new version watch the permissions and owner are the same as the original file
if neccessary change with chown and/or chmod +775
sudo hb-service start

works like a charm

**Comment by GravityRZ** [comment]
good workaround @Naqua 
i had to do it inside a docker container but it seems to work

also it looks like this problem was solved 2 months ago but somehow did not end up in the build we download

**Comment by Madcat-76310** [comment]
Hi,
To do this : replace domoticz.js with the new version
Which command you used ?
Thanks

**Comment by PvdGulik** [comment]
I tried the following, but no succes:

cd /var/lib/homebridge/node_modules/homebridge-edomoticz
ls -l
git pull
cd lib
ls -l
rn domoticz.j domoticz.js.old
mv domoticz.j domoticz.js.old
mv domoticz.js domoticz.js.old
sudo mv domoticz.js domoticz.js.old
ls -l
git get https://github.com/PatchworkBoy/homebridge-edomoticz/blob/master/lib/domoticz.js
grep https://github.com/PatchworkBoy/homebridge-edomoticz/blob/master/lib/domoticz.js
cd ..
ls -l
cd ~
ls -l
cd /var/lib/homebridge/node_modules/homebridge-edomoticz
ls -l
cd lib
ls -l
cd ~
exit

Maybe I did something wrong?
Thanks!

**Comment by Madcat-76310** [comment]
Same problem... i've tried git get / grep (after sudo hb-service stop), without success. edomoticz is the problem...

**Comment by GravityRZ** [comment]
i just downloaded the domoticz.js file from github(the raw version) so no git get command, just using the browser GUI
moved it to  a place which is shared with the homebridge container
went to the lib subdirectory 
/homebridge/node_modules/homebridge-edomoticz/lib
replaced the file
done

**Comment by Madcat-76310** [comment]
Ok, i used scp from my iMac to send the file on a Virtual Machine (Freebox Delta) after downloading the file domoticz.js on my Mac.
Command used in the iMac terminal : scp domoticz.js freebox@192.168.X.YYY:/home/pi
But same error message : Domoticz deprecated...

**Comment by GravityRZ** [comment]
/home/pi is not where homebridge is running or is it.

you need to find out where homebridge is running
THIS IS NOT A DOMOTICZ PROBLEM
look at the post from Naqua.
findout where Homebridge is runnning, go to that directory, goto the lib directory
there should be a domoticz.js file which you need to replace with the new one.

i run homebridge in a container and it looks like this

![image](https://github.com/PatchworkBoy/homebridge-edomoticz/assets/16853535/e70d8d77-cb49-4541-8c44-595e28fbed72)

**Comment by Madcat-76310** [comment]
Yes, /home/pi was just a step (for showing how to use scp), i've copyied domoticz.js to  /homebridge/node_modules/homebridge-edomoticz/lib (after making a domoticz.js.old backup). I'm agree with you, it's not a domoticz problem. I suspect it was homebridge-edomoticz because the other plugins are all inactives.

**Comment by PvdGulik** [comment]
That's what I also tried, but failed.
I'll try again today
________________________________
Van: GravityRZ ***@***.***>
Verzonden: zaterdag 26 augustus 2023 16:55
Aan: PatchworkBoy/homebridge-edomoticz ***@***.***>
CC: Tebogo ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [PatchworkBoy/homebridge-edomoticz] API Calls to Domoticz depricated (Issue #265)


i just downloaded the domoticz.js file from github(the raw version) so no git get command, just using the browser GUI
moved it to a place which is shared with the homebridge container
went to the lib subdirectory
/homebridge/node_modules/homebridge-edomoticz/lib
replaced the file
done

**Comment by marktn** [comment]
This is new for me, how to find the new domoticz.js file, and replace it?

This is the location,
![afbeelding](https://github.com/PatchworkBoy/homebridge-edomoticz/assets/11601535/ee6ce41e-4ed6-4da1-b240-1fb5ff1028c4)

**Comment by GravityRZ** [comment]
> This is new for me, how to find the new domoticz.js file, and replace it?
> 
> This is the location, ![afbeelding](https://user-images.githubusercontent.com/11601535/263812889-ee6ce41e-4ed6-4da1-b240-1fb5ff1028c4.png)

from that directory
cd lib
ls -l

the domoticz.js file you see is the one you need to replace.

it looks like you are not in a container so download the correct file like decribed earlier and copy it to this lib directory
looking at other people somehow git get does not work so just download it by using a browser and find a way to copy it

**Comment by marktn** [comment]
Thanks,

Unfortunately it does not work:
password never changed. did try raspberry and admin.


C:\Windows\System32>scp domoticz.js pi@192.168.1.185:lib/
pi@192.168.1.185's password:
Permission denied, please try again.
pi@192.168.1.185's password:
Permission denied, please try again.
pi@192.168.1.185's password:
pi@192.168.1.185: Permission denied (publickey,password).
lost connection

C:\Windows\System32>

**Comment by Madcat-76310** [comment]
I'm not lucky, really 👍🏻 ERROR LOADING PLUGIN homebridge-edomoticz:
[9/4/2023, 5:05:21 PM] Error: Cannot find module 'request'
Require stack:
- /var/lib/homebridge/node_modules/homebridge-edomoticz/lib/domoticz.js
- /var/lib/homebridge/node_modules/homebridge-edomoticz/index.js
- /var/lib/homebridge/node_modules/homebridge/lib/plugin.js
- /var/lib/homebridge/node_modules/homebridge/lib/pluginManager.js
- /var/lib/homebridge/node_modules/homebridge/lib/server.js
- /var/lib/homebridge/node_modules/homebridge/lib/cli.js
- /var/lib/homebridge/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Function.Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/var/lib/homebridge/node_modules/homebridge-edomoticz/lib/domoticz.js:1:15)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
[9/4/2023, 5:05:21 PM] ====================

**Comment by PatchworkBoy** [comment]
Merges now published up to NPM.

**Comment by Madcat-76310** [comment]
Problem solved with with [homebridge-domoticz-selector-switch] using this method :
Useful if you use old and not maintened plugins

1°) Connect to Raspberry / VM / or other with ssh terminal
2°) Go to /var/lib/homebridge/node_modules/
3°) Enter your plugin directory which give problem
4°) Use sudo nano index.js (to edit the code)
5°) Make correction using wiki : https://www.domoticz.com/wiki/Domoticz_API/JSON_URL's
6°) Save / Close nano and reboot your system
