### ISSUE TITLE
Switchtype selector

### ISSUE THREAD

**Issue by arcidodo** [PatchworkBoy/homebridge-eDomoticz#34]
Hi! thanks for the plugin so far! its working great!! but i just made an switch to control my TV. is it possible with homekit to have an switch with more options? like this one below?

![schermafbeelding 2016-08-15 om 14 32 54](https://cloud.githubusercontent.com/assets/678514/17664555/3a786be2-62f5-11e6-8ad4-36e4cc6b5fd9.png)

`

      {
         "AddjMulti" : 1.0,
         "AddjMulti2" : 1.0,
         "AddjValue" : 0.0,
         "AddjValue2" : 0.0,
         "BatteryLevel" : 255,
         "CustomImage" : 2,
         "Data" : "Off",
         "Description" : "",
         "Favorite" : 1,
         "HardwareID" : 7,
         "HardwareName" : "Virtuele switch",
         "HardwareType" : "Dummy (Does nothing, use for virtual switches only)",
         "HardwareTypeVal" : 15,
         "HaveDimmer" : true,
         "HaveGroupCmd" : true,
         "HaveTimeout" : false,
         "ID" : "0001415A",
         "Image" : "TV",
         "IsSubDevice" : false,
         "LastUpdate" : "2016-08-15 13:47:44",
         "Level" : 0,
         "LevelActions" : "script%3A//request.sh%20off|script%3A//request.sh%20on|script%3A//request.sh%20hdmi1|script%3A//request.sh%20hdmi2",
         "LevelInt" : 0,
         "LevelNames" : "Off|TV|Apple TV|PS4",
         "LevelOffHidden" : false,
         "MaxDimLevel" : 100,
         "Name" : "TV Selector",
         "Notifications" : "false",
         "PlanID" : "0",
         "PlanIDs" : [ 0 ],
         "Protected" : false,
         "SelectorStyle" : 0,
         "ShowNotifications" : true,
         "SignalLevel" : "-",
         "Status" : "Off",
         "StrParam1" : "",
         "StrParam2" : "",
         "SubType" : "Selector Switch",
         "SwitchType" : "Selector",
         "SwitchTypeVal" : 18,
         "Timers" : "false",
         "Type" : "Light/Switch",
         "TypeImg" : "Light",
         "Unit" : 1,
         "Used" : 1,
         "UsedByCamera" : false,
         "XOffset" : "0",
         "YOffset" : "0",
         "idx" : "267"
      },`

**Comment by PatchworkBoy** [comment]
Nope. Fraid not.

**Comment by ooii** [comment]
Hi @PatchworkBoy, I read your post on [domoticz forum](http://domoticz.com/forum/viewtopic.php?t=22015) and I'm wondering if there is not a workaround to have a selector switch in Homekit. 
What about exposing a selector switch as a thermostat? This type of accessory/device is recognized by Homekit which offers the ability to select a mode.
I'm asking that because exposing each state of the selector as an individual domoticz switch will increase the number of devices exposed to Homekit which leads to a quick reach of the configuration sync limit between Homekit devices (around 120 devices).

**Comment by ooii** [comment]
Okay. Thanks.
Hope Apple will add this type of switches soon.
