### ISSUE TITLE
update

### ISSUE THREAD

**Issue by m0rph13** [PatchworkBoy/homebridge-eDomoticz#7]
Hi!
Awesome plugin!

Was just to update the plugin when I ran into this irritating issue:

When executing the following command:
`>sudo npm update -g `
I got:
```
npm ERR! Linux 4.1.14-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update" "-g"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/homebridge-eDomoticz
npm ERR! 404 
npm ERR! 404 'homebridge-eDomoticz' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404 
npm ERR! 404  1. name can no longer contain capital letters
```

**Comment by PatchworkBoy** [comment]
Yeah - not sure how to get npm update working from GitHub. For now just npm uninstall -g homebridge-eDomoticz && npm install -g patchworkboy/homebridge-eDomoticz

**Comment by PatchworkBoy** [comment]
Will fix the package name case thang in an hour or so when I'm back near a computer...

**Comment by PatchworkBoy** [comment]
I _think_ this is sorted now. I’ve published it all to the npm registry rather than brute forcing from github. (This is all my first time using node / npm / github properly - soz!)

`npm uninstall -g homebridge-eDomoticz && npm install -g homebridge-edomoticz`

...should get rid of current version, grab latest via the registry, and then allow you to use...

`npm update -g homebridge-edomoticz`

...to grab latest updates from that point forth. Obvs, restart homebridge after doing all this to pick up the changes.

Give it a whirl n’ let me know if it works...

**Comment by m0rph13** [comment]
Works!

**Comment by PatchworkBoy** [comment]
Heh - I made a mess of that... update it again.
