### ISSUE TITLE
Slow to update status and sensor

### ISSUE THREAD

**Issue by marcotini** [PatchworkBoy/homebridge-edomoticz#76]
I notice that it's too slow to update the status of the light and the sensor (like Xiaomi, Yeelight or Hue).

Sometimes I also need to close and reopen the app Home to see the change. I say so because if I use the homebridge-aqara (for example), the door or human sensor became trigger instantly.

There is somethings to do for make all instantly updated?

Edit: now I noticed that this plugin make the sensor in a fake state on when they are not (I'm talking about door and motion sensor). How can be possible? Maybe some timeout or heartbeat?

**Comment by xTheRamon** [comment]
I'll try to improve the speed! Keep you updated...

**Comment by xTheRamon** [comment]
Try and update to the latest version of homebridge and homebridge-edomoticz. Use `npm update` to update all the modules.

For me the speed has drastically improved with the latest updates.

**Comment by marcotini** [comment]
When I open and close the door, the sensor is not change immediately (I mean, not like this one https://youtu.be/J4cOUE62aS0).

**Comment by xTheRamon** [comment]
Can I have a look at your config file in the ~/.homebridge Directory?

**Comment by marcotini** [comment]
It's just: 

`{
            "platform": "eDomoticz",
            "name": "eDomoticz",
            "server": "127.0.0.1",
            "port": "8080",
            "ssl": 0,
            "roomid": 2,
            "mqtt": 0
       }
`

The plugin used in the video is this one https://github.com/snOOrz/homebridge-aqara and it's update instantly.

**Comment by xTheRamon** [comment]
I think I know where your problem lies. You're not using MQTT for communications between Domoticz and the plugin, so the HomeBridge app 'asks' the Domoticz for updates every 'x' seconds. This feels slow.

If you start using MQTT, the updates will come in like 'push messages', instantly.

To start using MQTT follow these simple steps:

- Install Mosquitto on your server.
This is a MQTT broker which will 'host' the MQTT connections.

- Configure Domoticz and add new hardware: `MQTT Client Gateway with LAN interface`.
If you have installed Mosquitto on the same server as Domoticz, use 'localhost' for the remote address. Use `1883` for the port. Publish topic: out

- Update `~/.homebridge/config.json` and set `"mqtt": 1`

- Restart Homebridge and try again! 👏

**Comment by marcotini** [comment]
Ok lol now work like a charm.

I just need to create the user (sorry but I don't know so well Mosquitto), in case you want to add in the Wiki:

```
sudo service mosquitto stop
sudo mosquitto_passwd -c /etc/mosquitto/pwfile user
sudo service mosquitto start
```

**Comment by xTheRamon** [comment]
Nice, so good to hear!! Wiki would be a good idea. Thanks a bunch!
