### ISSUE TITLE
Device status updates in the home application

### ISSUE THREAD

**Issue by djrams10** [PatchworkBoy/homebridge-edomoticz#97]
The status of door contactors and movements are very long to update. Does anyone have the solution to this problem? thank you very much

**Comment by simonrb2000** [comment]
Is it just those or is it all devices? I've noticed that changes either don't happen or take a while if the home app is open..

**Comment by djrams10** [comment]
Thank you for your answer. These are all devices that are in domoticz. Even if the home application is open, the response time is very long

**Comment by xTheRamon** [comment]
@djrams10  Are you using MQTT by any chance? Please check `~/.homebridge/config.json`.

**Comment by simonrb2000** [comment]
Mine was due to me not running MQTT when I thought I was! Mines fine now I updated my config file

**Comment by djrams10** [comment]
thank you. How do you configure mqtt? thank you

**Comment by djrams10** [comment]
Thanks for your help, I installed homebridge on a synology. With docker.

**Comment by djrams10** [comment]
I'm french, sorry for my english.

**Comment by xTheRamon** [comment]
@djrams10 Please read the following: https://github.com/PatchworkBoy/homebridge-edomoticz#configuration

**Comment by madcat-nl** [comment]
i also encountered this issue before, after installing the MQTT service.
Do not forget to add the hardware, you probably will see an error like this: [eDomoticz] There was an error while getting the MQTT Hardware Device from Domoticz.
Please verify that you have added the MQTT Hardware Device and that the hardware device is enabled.

this will explain how:
https://www.domoticz.com/wiki/MQTT#Add_hardware_.22MQTT_Client_Gateway.22

when you have done it correctly homebrige you should say: [eDomoticz] Successfully connected to MQTT broker.

Then the IOS devices will be updated near realtime instead of when you request an update.

**Comment by djrams10** [comment]
Thank you all for your help. MQTT is it possible to use it with a synology? Thank you. The homebridge version is 0.4.25. Is this the right one? Because I always have the same problem.

**Comment by xTheRamon** [comment]
@madcat-nl Thank you for your explanation. Good add!

@djrams10 MQTT on Synology should not be a problem. Also your homebridge version seems OK as it is the latest version. 👍🏼
